stages: 
  - build
  - deploy
.default: &DEFAULT
  tags: [ cluster ]

.build: &BUILD
  <<: *DEFAULT
  tags: [ cluster ]
  stage: build
  script:
    - pacman -Syy
    - echo "Server = https://mirror.fsrv.services/pub/archlinux/$repo/os/$arch" > /etc/pacman.d/mirrorlist
    - pacman -Syy --noconfirm go
    - go build goproxy.go
  artifacts:
    when: always
    paths:
      - "goproxy"
  image: archlinux

amd64:openbsd:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: openbsd
amd64:freebsd:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: freebsd
amd64:linux:
  <<: *BUILD
  variables:
    GOARCH: amd64
    GOOS: linux

